name: Tiny Tapeout CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tiny Tapeout Validation
        uses: TinyTapeout/tt-gds-action@tt10
